name: PR Format

on:
  pull_request:
    branches:
      - master
    paths:
      - "**/*.md"

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run Prettier format
        run: npx prettier --write "./**/*.md"

      - name: Check for changes
        id: git_diff
        run: |
          git diff --exit-code || echo "changes"

      - uses: stefanzweifel/git-auto-commit-action@v6
        if: steps.git_diff.outputs.changes == 'changes'
        with:
          commit_message: Apply Prettier Change
